name: Tests

on: [push]

jobs:

  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set path for MacPorts
        if: runner.os == 'macOS'
        run: echo "::add-path::/opt/local/bin"

      - name: Install gfortran on Ubuntu
        if: runner.os == 'Linux'
        run: sudo apt install gfortran

      - name: Install X11 from MacPorts
        if: runner.os == 'macOS'
        run: |
          curl -O https://distfiles.macports.org/MacPorts/MacPorts-2.6.2.tar.bz2
          tar xf MacPorts-2.6.2.tar.bz2
          cd MacPorts-2.6.2/
          ./configure
          make
          sudo make install
          sudo port selfupdate
          sudo port install xorg

      - name: Compile XFOIL
        run:  ./compile.sh

      - name: Install dependencies for test
        run: pip install pytest numpy

      - name: Tests
        run: python -m pytest tests

      - uses: actions/upload-artifact@v1
        with:
          name: xfoil-${{ runner.os }}
          path: ./bin